### ISSUE TITLE
injector 跑不起来。。

### ISSUE THREAD

**Issue by QGB** [vito11/CameraHook#3]
root@X9180:/data/data/com.vito.research.camerahook # ll
drwxrwx--x u0_a93   u0_a93            2018-12-21 08:32 cache
drwxrwx--x u0_a93   u0_a93            2018-12-21 08:49 files
-rwxrwxrwx u0_a93   u0_a93          0 2018-12-21 10:09 injector
lrwxrwxrwx install  install           2018-12-21 10:08 lib -> /data/app-lib/com.vito.research.camerahook-1
root@X9180:/data/data/com.vito.research.camerahook # ./injector
tmp-mksh: ./injector: Text file busy
1|root@X9180:/data/data/com.vito.research.camerahook # ./injector
tmp-mksh: ./injector: Text file busy

127|root@X9180:/data/data/com.vito.research.camerahook # ps |grep inject
1|root@X9180:/data/data/com.vito.research.camerahook #
1|root@X9180:/data/data/com.vito.research.camerahook #

**Comment by vito11** [comment]
To test this demo, I believe you should import the whole project into Android Studio IDE to build a complete application. You can not separately run the injector.
